apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
  name: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
spec:
  replicas: 1
  selector:
    matchLabels:
      run: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
      app: ORDERS
  template:
    metadata:
      labels:
        run: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
        app: ORDERS
    spec:
      hostname: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
      containers:
        - name: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
          image: latonaio/convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
          imagePullPolicy: Always
          env:
            - name: "RMQ_QUEUE_FROM"
              value: "data-platform-api-orders-creates-queue-from"
            - name: "RMQ_QUEUE_TO_SQL"
              value: "sql-update-kube"
            - name: "RMQ_QUEUE_TO_EX_CONF"
              value: "data-platform-api-business-partner-exconf-queue"
            - name: "RMQ_QUEUE_TO_HEADERS_SUB_FUNC"
              value: "data-platform-api-orders-headers-creates-subfunc-queue"
            - name: "RMQ_QUEUE_TO_ITEMS_SUB_FUNC"
              value: "data-platform-api-orders-items-creates-subfunc-queue"
            - name: "RMQ_SESSION_CONTROL_QUEUE"
              value: "data-platform-api-orders-creates-session-control-queue"
            - name: "DB_NAME"
              value: "DataPlatformMastersAndTransactionsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
  name: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
spec:
  selector:
    run: convert-to-dpfm-payment-requisition-mitsubishi-from-dpfm
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30748
